### ISSUE TITLE
Is it possible to load sqlite extensions?

### ISSUE THREAD

**Issue by aborruso** [xo/usql#103]
Hi,
first of all thank you for this tools.

In sqlite, via `.load`, it's possible to load extensions https://www.sqlite.org/loadext.html

Is it possible to do it via usql?

Thank you

**Comment by kenshaw** [comment]
No, this is a feature of the `sqlite3` command line tool, and dynamic libraries can't be loaded by `usql` due to a number of underlying reasons. Please note that most of the extensions bundled with sqlite3, and made available via the underlying `github.com/mattn/go-sqlite3` driver are enabled by default in the release builds of `usql`. Additionally, they can be built/compiled using Go (please see the `gen-release.sh` for the list of tags used). If you wanted to build and statically add a sqlite3 C extension, that would entirely be plausible too.
