### ISSUE TITLE
Any suggestions on how to connect to DB2/Tibero instances?

### ISSUE THREAD

**Issue by chakri-stark** [xo/usql#108]
Hi @kenshaw ,
In Linux, I have used odbc+DB2 to connect to the DB2 instance. Thanks for the going an extra mile and providing a Dockerfile for DB2 instance. Can I use a similar approach to connect to Tibero?
Apart from that, Can you elaborate on how to use adodb to connect to DB2 in windows? And can we apply this adodb process on Tibero too?

Thanks,
Chakri

**Comment by kenshaw** [comment]
I've never heard of Tibero until just now. If they provide a ODBC driver, `usql` should be able to connect to it through the ODBC driver. You would need to configure/set up your ODBC driver on your system as instructed via ODBC. You can look in the `contrib/db2` folder which gives some example configuration settings for ODBC. If you can't get the `isql` tool to connect to Tibero with ODBC, then `usql` won't be able to either.

**Comment by chakri-stark** [comment]
I will give a try with their ODBC driver if any and will update for Tibero.
Any thoughts on Windows usage of DB2?

**Comment by kenshaw** [comment]
Check via the "Control Panel" (I know modern Win10 doesn't really have this anymore) if the Tibero driver is configured and installed. I must admit I don't use Win10/ODBC often, so I won't be of much use. For what it's worth, I have in the past successfully used `usql` with MySQL, PostgreSQL, DB2, and Oracle using their respective ODBC drivers for Windows. It's been well over 2 years since I last tried, but I see no reason it shouldn't be usable still.

**Comment by chakri-stark** [comment]
In this [old issue](https://github.com/xo/usql/issues/87), you have mentioned usage of DB2 along with adodb rather than ODBC. So, I am confused about which one to use? Can you please explain a bit elaborated on how to use it?

> Quoted from Issue 87:
> Note that on Windows, we don't use the CGO ODBC driver, but use ADODB's driver, and build a DSN using ADODB as the driver, but telling ADODB to use the ODBC driver.

**Comment by kenshaw** [comment]
ODBC is a bit different the rest of the other drivers that `usql` supports. On non-Windows system, the underlying library it uses is UnixODBC, on Windows `usql` maps the ODBC URLs to ADODB, because UnixODBC is not available on Windows. 

On Windows, any ODBC registered provider is made available to ADODB, which in concept works very similarly to ODBC. I forget which specific generation of Microsoft Database Marketing/Technology is the underlying provider (JET/MSDE/ACE/...) to ADODB, but suffice it to say, ODBC drivers are exposed through a registered ADODB interface. Microsoft had done this (IIRC) so that ADO.NET would work properly with any ODBC driver, and thus any .NET program would be able to connect to any database that had a Windows ODBC driver. 

It's possible you may need to install JET/MSDE/ACE/... or whatever drivers, but it's likely your database provider already included that with your ODBC driver installation. Please refer to your database vendor's documentation on how to build a ADODB DSN / connection string. If you can't connect through, eg, a VBScript or some other mechanism using the ADODB bridge/driver, then `usql` will not be able to either.

I apologize I can't be of more help, but I haven't actively been using Windows as a development platform since the late 90s.

I can suggest trying this though:

```sh
usql "adodb://Microsoft.ACE.OLEDB.12.0/?Extended+Properties=\"Text;HDR=NO;FMT=Delimited\"" \
  -c "create table example.csv(f1 text, f2 text, f3 text);" \
  -c "insert into example.csv(f1, f2, f3) values ('a', 'b', 'c');" \
  -c "select * from example.csv;"
```

If the above doesn't work work with `usql` on Windows, then you have either not built `usql` with ADODB, and/or you likely do not have all of the various driver chains (ODBC, ACE, OLEDB, ...) installed/configured properly on Windows.

(ps: the above was taken from the `contrib/adodb` folder in `usql`'s source, which I had used for testing connectivity end-to-end through ADODB. It should create a `example.csv` file in the current working directory, and then insert three values (a, b, c) into that CSV. If there are any errors produced by `usql` please copy/paste them here and I'll try to help debug them. If the error is along the lines of "cannot find Microsoft.ACE.OLEDB.12.0 driver" then you likely do not have all of the requisite components installed on your Windows system)

**Comment by kenshaw** [comment]
I just checked the actual implementation, and the behavior is this: 

On Windows, `usql` uses the alexbrainman `odbc` driver if it was built with the `odbc` build tag, and will use that natively for `odbc://` URLs. If `usql` was not built with `odbc` support on Windows, but `adodb` support is available, then `odbc://` and `oleodbc://` URLs will be opened with the `adodb` driver. 

That is, `usql` supports both ADODB and ODBC natively on Windows.

The reason I implemented it this way, is that the connectivity path for ODBC on Windows is more or less the same as ADODB, and one is more likely to have Microsoft Office installed than the native ODBC drivers. Microsoft Office registers ADODB drivers during installation, or if one does not have Microsoft Office, one can easily download the ADODB components from Microsoft and install. However, ODBC drivers are locked to a specific vendor.

Please check/verify you're able to connect with either the OLE ODBC, or ADODB drivers on Windows to your database. If either of those work, then `usql` should be able to connect as well. Crafting a DSN can be a bit tricky. In that case, one can always build the DSN passed to the underlying Go driver manually, and use the `\connect` (alias `\c`) metacommand in `usql` to connect:

```sh
$ usql
(not connected)=> \connect odbc <DSN>
```

**Comment by chakri-stark** [comment]
In the Linux platform, I have tried connecting to the DB2 instance using the so files from ibm_data_server_driver_for_odbc_cli.tar.gz.
I am facing the following errors while connecting as following:
If username alone is provided: ./usql odbc+DB2://username@IP:port/dbname
error: odbc: SQLDriverConnect: {08001} [IBM] [CLI Driver] SQL30082N security processing failed with reason "17" ("UNSUPPORTED FUNCTION). SQLSTATE=08001
If both username and password is provided: ./usql odbc+DB2://username:passwd@IP:port/dbname
error: odbc: SQLDriverConnect: {08001} [IBM] [CLI Driver] SQL1336N The remote host "LOCALHOST" was not found. SQLSTATE=08001

**Comment by chakri-stark** [comment]
I have done some debugging and found that it may be due to the Authentication protocol. Please share your insights!!

**Comment by chakri-stark** [comment]
Hi @kenshaw 
Any modifications to be done from usql side regarding the above error? Please suggest!

**Comment by kenshaw** [comment]
@chakri-stark the issue here is that you are likely not configuring your ODBC entry properly. With ODBC, it doesn't matter what parameters you use on the URL, the passed parameters may or may not override what you have configured in your actual ODBC configuration (I believe that's `/etc/odbcinst.ini` usually). If you're not able to connect using the `isql` command (the CLI that comes with ODBC), it's highly unlikely that you'll be able to get `usql` to connect.

I've done fairly extensive testing with DB2 and ODBC (in fact, DB2 is the primary reason I have included the ODBC driver for `usql`). Please checkout `usql`'s contrib/db2 folder. I had written that for the 11.1 version, and haven't yet updated the config for 11.5, but the steps should be more or less the same.

**Comment by chakri-stark** [comment]
My bad!! It's working properly in Linux. Thanks
