### ISSUE TITLE
Driver specific execMap

### ISSUE THREAD

**Issue by Preston4tw** [xo/usql#114]
Greetings,

I'm playing with usql with the Snowflake driver. I noticed that drivers/qtype.go has `var execMap` and `QueryExecType()` which determine if a query should be run as Exec() or Query(). I'd like to improve this for the Snowflake driver, as alter statements currently throw a golang db error:
```
alter session set ...
error: snowflake: no RowsAffected available after DDL statement
```

It seems like it might make sense to implement this at the driver level during driver registration as not all SQL dialects will necessarily be compatible. I wanted to get some thoughts from the maintainers  before I started touching code to see what approach if any is preferred.

**Comment by kenshaw** [comment]
Appreciate your work/support/interest on `usql` for Snowflake. As you've seen, support for the non-5 major SQL databases is fairly minimal, as it's just not possible for me to test all the various possible queries that each database can support. You are 100% correct in your thinking that `drivers.queryMap` and `drivers.execMap` were meant as a way for each driver to change whether or not a query/exec is performed on behalf of `usql`'s handler (`handler.Handler`).

So -- couple things: looking at `drivers/qtype.go` just now, I realize there's a fair bit of work necessary to make it work for different drivers. I'm happy to entertain a PR for that, and/or willing to work with you to initial implement it so that queries on Snowflake can be delegated to query/exec maps provided by Snowflake. For that, I'd need a sample of a few queries that are not currently working properly on Snowflake, so that I can figure out if it actually needs a full delegation to the driver or not. if it's simply `SESSION SET`, then all that should be necessary is to add it to the `execMap` in the same way as the minor variants for the `cassandra` and `ql` drivers sit next to the primary entries for PostgreSQL.

Unfortunately, this ham-fisted "exhaustive" list query/exec maps is really the only way to make this work with Go's SQL driver implementation, since there are just too many variations between all the various databases. For example, SQLite3's `PRAGMA`  can be both a query and an exec. I assume some of the other various `SESSION SET` DDL statements in the other databases are not being properly recognized either.

I would of course like `usql` to work perfectly with every database, but there is just no possible way I can test/scrutinize every database as it requires being proficient/expert in every database.

**Comment by Preston4tw** [comment]
Totally understood on the minimal support for the other drivers. I think this is a really cool project and I was surprised to see Snowflake was called out at all! The primary CLI for interacting with Snowflake, snowsql, is built on top of our python connector. I was looking to see how difficult it might be to write a Snowflake CLI based on our golang connector when I stumbled across this project: hence my interest.

I think a lot of the DDL statements could be covered with the broad prefixes: create, alter, drop, use, set, unset. I suspect that would be problematic if set globally though. There are a handful of other misc keywords for transactions: begin, commit, rollback.

```
sf:preston4tw@test=> create database preston4tw;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> alter database preston4tw rename to pbtest;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> show databases like 'pbtest';
 created_on                    | name   | is_default | is_current | origin | owner        | comment | options | retention_time 
-------------------------------+--------+------------+------------+--------+--------------+---------+---------+----------------
 2020-01-24T10:14:32.497-05:00 | PBTEST | N          | N          |        | ACCOUNTADMIN |         |         | 1              
(1 row)

sf:preston4tw@test=> use database pbtest;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> begin
sf:preston4tw@test-> ;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> rollback;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> set x = 'asf';
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> unset x;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=> drop database pbtest;
error: snowflake: no RowsAffected available after DDL statement
sf:preston4tw@test=>  
```

Hmm now that I'm comparing the output with qtype.go, the create/drop statements shouldn't be erroring. It's not a case sensitivity thing, I tested in upper case as well. Looking at drivers/oracle/oracle.go it looks like a Process func needs to be registered in the Snowflake driver as well.

**Comment by kenshaw** [comment]
Is [`RowsAffected`](https://godoc.org/database/sql#Result) supported by Snowflake Go driver? Note that this can be hooked by `usql` drivers, in order to override the behavior of the underlying database. For example, ignoring an error tossed by the actual driver:

```diff
diff --git a/drivers/snowflake/snowflake.go b/drivers/snowflake/snowflake.go
index 46fe149..8e169b4 100644
--- a/drivers/snowflake/snowflake.go
+++ b/drivers/snowflake/snowflake.go
@@ -1,7 +1,9 @@
 package snowflake
 
 import (
+	"database/sql"
 	"strconv"
+	"strings"
 
 	// DRIVER: snowflake
 	"github.com/snowflakedb/gosnowflake"
@@ -17,5 +19,15 @@ func init() {
 			}
 			return "", err.Error()
 		},
+		RowsAffected: func(res sql.Result) (int64, error) {
+			count, err := res.RowsAffected()
+			switch {
+			case err != nil && strings.TrimSpace(err.Error()) == "no RowsAffected available after DDL statement":
+				return 0, nil
+			case err != nil:
+				return 0, err
+			}
+			return count, nil
+		},
 	})
 }
```

(please note I haven't tried the above; and I have no idea where that original error is coming from. It doesn't seem to be in the `gosnowflake` driver code)

**Comment by kenshaw** [comment]
Ah -- it appears to come from Go's `driver.ResultNoRows` var. The `usql` handler code should be changed to check if the returned result is equal to that value, and not try to call the driver's `RowsAffected` method.

**Comment by kenshaw** [comment]
I just pushed a minor fix to this in `drivers.RowsAffected` -- it should correctly ignore this now for any database driver that is "correctly" returning Go's `driver.ResultNoRows` value. I previously was not aware of this value, so I'm curious to know if this is relatively new, or if I had just missed it when I was writing the original driver code for `usql`.

(note: it appears I had missed this originally)

**Comment by kenshaw** [comment]
Please pull the latest code, and try out other DDL statements on Snowflake. Let me know if there are other issues. Closing this issue for now, assuming this is the root issue.

**Comment by Preston4tw** [comment]
Thanks, I'll try it! I got as far as finding that the error was coming out of the Golang library code. I was looking at the gosnowflake code trying to grok it. I also don't understand the golang database/sql interface that well yet. I do recall seeing in various golang release notes that the interface has had some additions and changes, so it's certainly possible. If I have any further issues I'll reopen.

**Comment by Preston4tw** [comment]
5c7fb6f with the patch in https://github.com/xo/usql/issues/114#issuecomment-578197874 works!

```
sf:preston4tw@test=> create database preston4tw;
CREATE DATABASE
sf:preston4tw@test=> drop database preston4tw;
DROP DATABASE
sf:preston4tw@test=> ^D
```
