### ISSUE TITLE
libicu dependency issue again

### ISSUE THREAD

**Issue by jetzerb** [xo/usql#117]
Installed usql binary release 0.7.8 on Ubuntu 20.04 (Focal).  Upon executing, I got an error:

```sh
$ usql --version
usql: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
```

This version of Ubuntu installs libicu6**5**.

This `libicu` dependency has caused issues in the past (#80, #82, #90).

I'm wondering if it's possible to relax the `usql` dependency to `libicuuc.so` rather than a specific version (_e.g._ `libicuuc.so.63`) so that if the host system is a couple versions ahead or behind, chances are very good that `usql` will function just fine.

Here's what `/usr/lib/x86_64-linux-gnu` looks like on Ubuntu 20.04:
```
libicudata.a
libicudata.so -> libicudata.so.65.1
libicudata.so.65 -> libicudata.so.65.1
libicudata.so.65.1
libicui18n.a
libicui18n.so -> libicui18n.so.65.1
libicui18n.so.65 -> libicui18n.so.65.1
libicui18n.so.65.1
libicuio.a
libicuio.so -> libicuio.so.65.1
libicuio.so.65 -> libicuio.so.65.1
libicuio.so.65.1
libicutest.a
libicutest.so -> libicutest.so.65.1
libicutest.so.65 -> libicutest.so.65.1
libicutest.so.65.1
libicutu.a
libicutu.so -> libicutu.so.65.1
libicutu.so.65 -> libicutu.so.65.1
libicutu.so.65.1
libicuuc.a
libicuuc.so -> libicuuc.so.65.1
libicuuc.so.65 -> libicuuc.so.65.1
libicuuc.so.65.1
```
If I manually create links for `libicuuc.so.63 -> libicuuc.so.65.1`, `usql` works again:
```sh
$ for lib in libicu*.so.65.1
do
   sudo ln -s $lib ${lib/65.1/63};
done;

$ ls -l libicu* | sed 's/.*:[0-9][0-9] //;'
libicudata.a
libicudata.so -> libicudata.so.65.1
libicudata.so.63 -> libicudata.so.65.1    <-- new link
libicudata.so.65 -> libicudata.so.65.1
libicudata.so.65.1
libicui18n.a
libicui18n.so -> libicui18n.so.65.1
libicui18n.so.63 -> libicui18n.so.65.1    <-- new link
libicui18n.so.65 -> libicui18n.so.65.1
libicui18n.so.65.1
libicuio.a
libicuio.so -> libicuio.so.65.1
libicuio.so.63 -> libicuio.so.65.1    <-- new link
libicuio.so.65 -> libicuio.so.65.1
libicuio.so.65.1
libicutest.a
libicutest.so -> libicutest.so.65.1
libicutest.so.63 -> libicutest.so.65.1    <-- new link
libicutest.so.65 -> libicutest.so.65.1
libicutest.so.65.1
libicutu.a
libicutu.so -> libicutu.so.65.1
libicutu.so.63 -> libicutu.so.65.1    <-- new link
libicutu.so.65 -> libicutu.so.65.1
libicutu.so.65.1
libicuuc.a
libicuuc.so -> libicuuc.so.65.1
libicuuc.so.63 -> libicuuc.so.65.1    <-- new link
libicuuc.so.65 -> libicuuc.so.65.1
libicuuc.so.65.1
$ usql --version
usql 0.7.8
$
```

**Comment by kenshaw** [comment]
The release was built on Ubuntu 19.10 (for what it's worth). Your workaround of making manual symlinks is fairly common when running a pre-release/early version of Ubuntu. For your specific environment, of living on the edge of 20.04, this is your easiest bet if you don't want to be bothered with building from source. Alternately, you can build from source. Additionally, if you feel like mucking with it (and assuming the API hasn't changed), you change the ld dependencies in the `usql` binary to the newer library.

SQLite3 is the only database driver in the `usql` release that requires any CGO dependencies. I've thought about it, and while I might consider not including SQLite3's ICU extension in future releases, I'd prefer not to as I think it makes `usql`'s releases significantly less useful. I'm also not able (at this time) to build/maintain package repositories (ie, a PPA) for multiple Ubuntu releases. I will however, contemplate doing 2 releases: one with CGO dependencies, and one without (and possibly built using `tinygo`, if that's even possible). However, that would mean the `tiny` release would _not_ have SQLite3 at all.

(as an aside: there is no great immediate general solution, since I believe if the ICU extension is not included in releases, there will be other issues added to GitHub such as "why does this query return different results on `usql` than it does on the `sqlite3` cli?")

**Comment by powerman** [comment]
Same issue on Gentoo Linux.

**Comment by kenshaw** [comment]
@powerman -- please see my previous comment. The easiest fix is to either do a symlink to those libraries, relink the executable, or build from source.

**Comment by powerman** [comment]
TBH it's bad idea to distribute non-static binary as a single binary. Especially in Go projects, when everyone already expect static binaries. I recommend to either don't provide a binary release at all, or have it include only drivers which compiles to static binary.

Yeah, I've built from source, but then I realized tab-completion isn't implemented yet, and without it this tool isn't as useful as it expected to be. :disappointed:

**Comment by kenshaw** [comment]
@powerman -- your comments are not helpful.

If you'd like to contribute and submit a PR with tab completion working for the 5 major databases, I'd include it in a heartbeat. Having a cli tool that works more or less the same for "all" databases is the primary goal of this project, not necessarily to have every single bell/whistle available. For what it's worth, I do have tab completion working for PostgreSQL (and no other database) on a branch that I've never made public. Until I am not able to support all 5 major databases (PostgreSQL, MySQL, Microsoft SQL Server, Oracle Database, SQLite3) with basically the same feature, I've chosen not to make it generally available.

`usql`, as a project, will never be able to fix the issue of dynamic/static dependencies, distribution versioning, and Go. There are too many other pieces of software (none of which are controlled by myself) that limit options. Between the option of "not distributing a release" and "distributing a release", I've chosen to distribute a release that has limitations -- in case it is helpful to others -- even if that means it does not work completely in all scenarios in its distributed binary form. 

To that end, the simplest and easiest way for _most_ people is to simply build from source, which is extremely straightforward to do, and is well documented in the project's `README.md`.

**Comment by powerman** [comment]
@kenshaw I'm sorry if my comment sounds offensive to you - this wasn't my goal. English isn't my native language, so please be charitable. I'll try to rephrase what I was trying to say.

There is an issue known as "misplaced hopes". This isn't a technical issue, but a psychological one. This project hit it twice in a row: glance look at README creates impression we'll get tab-completion (by phrase "context-based completion" in Overview section - and I'm not the only one, here is another few guys https://github.com/xo/usql/issues/31#issuecomment-372030280), and downloading binary of Go project creates expectation it'll be static binary which "just works", which wasn't the case.

I'm not trying to say you're doing anything wrong, at all! But I believe it's good idea to spend some time to fix the "misplaced hopes" issue - all you need to do is make it more clear in README and on releases page what there is no completion (yet), and binary isn't static (and probably never be).

**Comment by kenshaw** [comment]
@powerman it's free and open source. I don't know what expectations or hopes people have as this is not a commercial product. `usql` was made public simply because I thought others might find it helpful. If it's not useful to you, there are two options: contribute and make it useful, or don't use it. Comments such as yours are complaints, and a knock against open-source contributors.

I've tried to make it usable out-of-the-box for others -- for which, given the limited time and resources there are to work on `usql`, I think I've done about as admirable of a job possible. One of the reasons I chose to write this in Go, and not for example, standard C, was _because_ it is so easy for others to build Go applications. Complaining that it doesn't work on the least used Linux distributions (Gentoo + Ubuntu 20.04, which isn't anywhere near ready for use in production) is counter-productive, and serves no purpose that I can see, other than announcing to the world that, eg, someone uses Gentoo/Ubuntu 20.04. Those who choose to use those distributions should be aware that not all software is going to work out-of-the-box and should, _individually_, expect that they will need to build from source code on occasion. This is one of those occasions.
 
In the amount of time it took you to write the two previous comments you could have:

1) Written a PR changing the `README.md` to reduce "misplaced hopes"
2) Downloaded Go, and the `usql` source code and compiled from source on your platform with any configuration, in the process better documenting that and sharing on this issue for consumption by others

Both of the above would have consumed less time / effort than it took to write up your comments, and notably you chose to do neither. 

That said, I appreciate your comments and involvement, and I do take these issues to heart. I am currently looking at ways that I can prevent this breakage in the future (including building/maintaining packages for the major distributions and their long-term releases), but I do not want to create "misplaced hopes" that distribution packages will be available anytime soon (because, well, they won't be).

**Comment by zloeber** [comment]
This project looks promising for some devops tasks I'm looking to accomplish but I've run into this same library dependency issue described at the start of this thread. Pulling the latest binary from this repo's releases, then dropping it into my path gives the following:
```
usql: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
```
But pulling in the base deployment without additional databases like this provides a binary that exhibits no issues:
```
go get -u github.com/xo/usql
```
Perhaps simply releasing the base binary (in github releases) without all the additional database support along side the all-in-one release you already have would be sufficient?

**Comment by zloeber** [comment]
Oh, to add to my prior note, thanks for all of what is obviously a ton of work that has been put into this utility. I'm simply blown away by the number of databases supported and the scope of this project.

**Comment by kenshaw** [comment]
@zloeber the issue is simply the ICU version. It can be worked around (see my comments above), but by far the simplest/easiest way is to build from source code. Since the built binary version of this uses the OS' installed version, the only way to fix this would be to maintain package repositories for the various Linux distributions. I definitely might (will?) consider doing that in the future, but I simply don't have the time to get all of that done at the moment.

**Comment by josepowera** [comment]
@kenshaw  
Any possibility to release without sqlite support.. (as per your comment https://github.com/xo/usql/issues/117#issuecomment-592995593)

Maybe most users would be just as happy with that (at least here we use usql to connect to real DB servers).

**Comment by kenshaw** [comment]
@josepowera -- is there a problem building it without SQLite3 locally?

**Comment by zloeber** [comment]
I had no issues building it locally without the support. I was going to look into how one might do divergent releases using goreleaser and github workflows but unfortunately never got the bandwidth to figure out if that is possible in the same goreleaser run. It may be worth looking into using it anyway, it could simplify the binary release process a bit.

**Comment by ynezz** [comment]
> The release was built on Ubuntu 19.10 (for what it's worth).

@kenshaw How are you doing releases? It seems like you're using Ubuntu 18.04 LTS version for testing on Travis, wouldn't it make more sense to build release for the same Ubuntu version? FYI I'm for example using 18.04 LTS and I'm unable to use the binary out of the box as well.

**Comment by ynezz** [comment]
FWIW I've tried that libicu symlink approach, but it doesn't work:

```
./usql: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./usql)
./usql: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./usql)
```

**Comment by borrrden** [comment]
I'll chime in here and say that first of all I think it is insane that Linux distros subject us to this torment in the first place.  There is no reason for the ICU API change other than "we feel like it" and actually it can be disabled when building from source.  I'm working around this issue on my side by making an explicit build for each distro that we support for now, but there is another way to handle this that I'd like to suggest (in fact this is what Android does):

Don't link against *any* libicu and instead attempt to find the library at runtime.  The filename has the version number built into it.  Append the version number to all of the ICU methods that you need and then look them up with `dlsym`.  It's technically more fragile but I've been using this method on Android for 5 years now without a hiccup and am about to commit time to doing it desktop Linux variants as well.  I thought perhaps you might find this technique useful.
