### ISSUE TITLE
TIME_FORMAT not being applied

### ISSUE THREAD

**Issue by calebeaires** [xo/usql#125]
USQL is amazing and simple to use. But at some point I am not used to. Like time format. Using the command line below time_format were not applied

```
usql my://root:root@localhost/flat -w --command "select * from flats" --set TIME_FORMAT="2006-01-02 15:04:05"
```

On the golang playground, the function do target I want

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	data := time.Now()
	fmt.Println(data.Format(("2006-01-02 15:04:05")))
}
```

The exemple above prints this = `2009-11-10 23:00:00`, that it what I first were looking for.

**Comment by nestor-custodio** [comment]
`TIME_FORMAT` can only be set to one of the [named Go language time layouts](https://golang.org/pkg/time/#pkg-constants), @calebeaires. None of the available formats matches what you're looking for exactly, unfortunately. The closest you'll find is probably "RFC3339".

**Comment by kenshaw** [comment]
I'm aware of the formatting issues. I don't have a specific date that I can share (I do the development in my spare time, of which I have little), but I am working on permanent fixes to the formatting / output / readline compatibility issues. It's slow going, and due to how I'm restructuring how a lot of this is done, it's not something that I can incrementally roll out.

**Comment by calebeaires** [comment]
Hey @kenshaw

Back here to get some follow about how this time formating feature is going! Thanks a lot for this project!
