### ISSUE TITLE
bash and zsh completions

### ISSUE THREAD

**Issue by nineinchnick** [xo/usql#209]
We could add another cli flag so that `usql` would output bash and zsh completions. This would be especially useful after being able to suggest connection strings (based on `.usqlpass`), which I'm doing for #65. Right now I'm only relying on the shell history.

**Comment by kenshaw** [comment]
`kingpin` already enables bash completion. It's more of a point of documenting this. It's worth noting, however, that the author of `kingpin` is instead maintaining his `kong` package instead of `kingpin`. They're roughly similar (I've used both), and it's probably worth cleaning up / doing a pass through the argument implementation. I don't really consider anything to be viable other than `cobra`, `kingpin` and `kong` as command-line packages. There isn't really any benefit to one vs. the other, and it's important here (in my opinion) to maintain as much compatibility with `psql` as possible.

**Comment by nineinchnick** [comment]
Cool, it kinda works. There's a lot of minor issues we could fix/improve:
* document how to use it, note that it requires `eval`, not `source`
* `--help` is not a regular flag, it's not in the output of `--help` and doesn't get completed
* we could use [the dymamic api](https://github.com/alecthomas/kingpin#additional-api) to add completions for the DSN; this is actually the main reason why I created this issue

**Comment by jgryko5** [comment]
I don't think that that would be possible using current `kingpin` library. Enabling `HintAction` function on the DSN argument works, but as soon as the user starts typing one of the suggested options, it isn't being detected as DSN anymore, so there aren't any suggested options.
