### ISSUE TITLE
usql --version gives me "usql 0.0.0-dev"

### ISSUE THREAD

**Issue by mckennagene** [xo/usql#291]
installed usql and the oracle go driver via ...

GO111MODULE=on go get github.com/xo/usql 
GO111MODULE=on go get -tags 'godror odbc' github.com/xo/usql 

trying to confirm i now have the latest version of usql, so i do this ...

~/go/bin/usql --version    

and it returns this
                                                
usql 0.0.0-dev

**Comment by kenshaw** [comment]
When you build from source, this is the version it's built with by default. The way `usql` is configured, is that you have to inject the `version` variable at build time to change this value. Please see `most.sh` in the repo root.

**Comment by mckennagene** [comment]
I'm sorry to be dense. I want to figure out how to ensure the version of usql i am running is the one i think it is. (0.9.4) so that I can properly report back on this issue https://github.com/xo/usql/issues/287

when i do usql --version i get 0.0.0-dev

Per your instructions, that is by design, and i need to inject the version. I am examining most.sh in pkg/mod/github.com/xo/usql@v0.9.4/most.sh and I see reference to -v and VER in here, but I don't understand what to do, and now I am surprised also my current output of "version" doesn't include the date based on what I see below. 

#!/bin/bash

# most.sh builds a development version of usql with "most" drivers.
#
# Options:
#  -i        go install instead of go build
#  -m        disable sqlite3 driver (no_sqlite3) and diasble CGO.
#            causes moderncsqlite to register aliases for sqlite3.
#  -v        add -v to go build/install
#  -x        add -x to go build/install
#  -t <TAG>  add build tag
#
# Usage: ./most.sh -i -t godror -v

NAME=usql
VER="$(date +%y.%m.%d)-dev"

**Comment by kenshaw** [comment]
No sweat, @mckennagene. Apologies that you're having trouble. Go changed how modules `go get` etc. work. I'll update the documentation soon. For now, this should work for you:

```sh
$ go install github.com/xo/usql@master
```

The reason that `go install` isn't working properly, is because in order to fix your original issue, I had to remove the `replace` directive in `go.mod`, but I have not yet tagged the most recent source changes. If you're working with/using `godror`, I would highly recommend installing/building directly from source and not trying to do `go install`. The easiest way (and the way that I use `usql` myself) is to simply use the `most.sh` script:

```sh
$ ./most.sh -i -t godror
```

Which I've tested extensively on Linux, macOS, and Windows (msys).
