### ISSUE TITLE
Error when data queried from oracle contains null

### ISSUE THREAD

**Issue by fgprodigal** [xo/usql#317]
usql oracle:xxxx:1521/orcl -c 'select null from dual'

Connected with driver oracle (Oracle Database 11.2.0.3.0)
error: oracle: TTC error: received code 14 during stmt reading

**Comment by kenshaw** [comment]
This is a limitation of @fgprodigal I believe this was a limitation of the `ora` driver, which has since been fixed. Please check the latest release version of `usql` to see if this issue still persists for you. I just checked against `Oracle Database 21.0.0.0.0` (see the `contrib/oracle` directory for the container config I use with Oracle) and it is working. It's worth noting that if you encounter issues like this with the `ora` driver, you can try using the `godror` driver instead.

```sh
ken@ken-desktop:~/src/go/src/github.com/xo/usql$ usql or://
Connected with driver oracle (Oracle Database 21.0.0.0.0)
Type "help" for help.

or:system@localhost/orasid=> select null from dual;
 null 
------
  
(1 row)

or:system@localhost/orasid=> \q
ken@ken-desktop:~/src/go/src/github.com/xo/usql$ usql godror://
Connected with driver godror (Oracle Database 21.0.0.0.0)
Type "help" for help.

gr:system@localhost/orasid=> select null from dual;
 null 
------
  
(1 row)

gr:system@localhost/orasid=> \q
```

**Comment by fgprodigal** [comment]
Problem solved! Appreciate
