### ISSUE TITLE
Connected with driver * should be written in stderr

### ISSUE THREAD

**Issue by mtxr** [xo/usql#34]
I think that would be useful to write anything that is not a SQL result to STDERR.

This is useful when you are writing scripts like:
`echo "show tables;" | ./usql mysql://user:pass@localhost:port/db 2> /dev/null`

I woul like to get just the query results.

**Comment by kenshaw** [comment]
@mtxr that's not a bad suggestion. In general, I would like to clean up how output is handled / finish implementing the output formatting / redirecting so that it works more similarly to `psql` (ie, being able to redirect to a file, etc). I also think that possibly a switch to turn this off would be warranted. `usql` deviates from `psql` on this because it's needed more for `usql` since you can connect to multiple/different databases in the same session. An setting / variable to change this behavior would probably be prudent.

**Comment by nineinchnick** [comment]
Note that you can work around this by adding `--set SHOW_HOST_INFORMATION=false`
