### ISSUE TITLE
pg_dump functionality

### ISSUE THREAD

**Issue by anarcat** [xo/usql#39]
Hi!

one killer feature of this would be to provide dump functionality. it wouldn't (at first) need to output portable SQL, as there's really no such thing: Postgres and MySQL might have some common set (especially for INSERT) but it will break down for indexes, table creations, stored procedures and whatnot.

still it would be nice to have a way to export the content of a database, even if it means reusing db-specific instructions... in my use case, i'm working with an embedded device where usql is one of the very select few commandline clients that works at all (thanks to the excellent golang cross-compilation features), so it would allow me to export (sqlite) databases from those devices and make a/b comparisons.

thanks!

**Comment by aplatypus** [comment]
I completely agree.  There's a real need for a udump program or similar.  Or a ``--dump`` option for tools such as `usql`.  For each supported database.

**Comment by kenshaw** [comment]
The likely equivalent in `usql` would be some kind of `\dump` meta command. The databases that `usql` supports are vastly too different to simply support this in kind of consistent fashion, and thus is not currently a goal of this project. Please note that `pg_dump` is _magic_ (I mean here the software/technical meaning of _magic_) in that it knows/understands the database and has full insight/knowledge/understanding of PostgreSQL's underlying data.

For illustration purposes, think of how `pg_dump` accurately dumps each and every database component -- indices, data, aggregates, types (the list goes on!). Expanding this to each and every major database (at minimum) would be beyond a herculean task.

Note that what's being requested here, is really a call for a _separate_ command-line tool that would be at least equal in complexity (and thus required authorship time) as `usql` itself. Additionally, for something as sensitive as dumping/restoring all data, I believe that's best left to the _native_ tools provided by each database.

**Comment by nineinchnick** [comment]
I think implementing `\copy` is much more realistic, that is to focus only on exporting data and leave dumping the full schema to dedicated tools.

The original description does mention to focus on the contents of the db. I'd like to suggest changing the issue title.

**Comment by kenshaw** [comment]
@nineinchnick the `\copy` command really isn't directly applicable to other databases as well. `usql` would need to deviate from `psql` here, as I do believe some kind of table dumping / copying would be prudent. I had looked at creating a concept of named connections in `usql`, so that one could connect to multiple connections at a time, something like this:

```sh
(not connected)=> \connect @host1 postgres://host1
@host1=> \connect @host2 mysql://host2
@host2=> select a, b from mysql_table  \copy @host1 my_table
```
The idea here that `\copy` would be like a `\g` command. Open to some kind of syntax suggestion. As it is, `psql` defines `\copy` as:
```
\copy ...              perform SQL COPY with data stream to the client host
```
So anything is possible, essentially. the actual SQL `COPY ...` is a server side implementation that gets used by the `psql` client that streams the data. You can use various SQL statements with `\copy` as well, but I haven't used this feature much. I completely get how it'd be great to have some kind of cross database functionality, but I have limited time to implement these things.

**Comment by nineinchnick** [comment]
I vote to close this issue as a WONTDO. The existence of a dump command implies that there's a restore command, which in turn implies that the round trip would be lossless, that is it can be used for reliable backups. This requires A LOT of data conversion code. I believe it's unreasonable to try to maintain it in a tool like `usql`, and it would be best to leave this to either native tools provided with the databases or other products/project specializing in backups.

Also, we now have the `\copy` command (#238), which comes with no guarantess on correctness and performance.

@kenshaw your last comment is a great idea, maybe you can create a separate issue for it?

**Comment by kenshaw** [comment]
Agree; whatever form of "dumping" we do will be done through `\copy` in some kind of form.
