### ISSUE TITLE
Oracle query output is getting garbled 

### ISSUE THREAD

**Issue by kishorerathi** [xo/usql#47]
Hello
I am observing a strange behavior with usql. I am running usql on ubuntu 16.04 LTS. I am connecting to an oracle instance. I issue a simple query and the output comes as expected, clear and clean. I issue the same query, and typically first two columns are garbled. portion of second column appears as appended to first column. If I execute the query again 3-4 times, display becomes OK but again gets garbled.

It is making the output unreliable as it becomes garbage.

I have syntax highlight set to False. For your reference I am attaching the screenshot. Please let me know if you need anything else.

Will appreciate a quick response so that I can continue using this useful tool.

regards
Kishore
![screenshot from 2018-04-27 21-51-33](https://user-images.githubusercontent.com/178602/39373787-4caf490c-4a66-11e8-8a6a-8acb5dacf844.png)

**Comment by kenshaw** [comment]
@kishorerathi appreciate you sharing this. I've looked into it, and I'm not sure exactly what is causing this for you. My guess is that it's not any of `usql`'s code, but likely an issue with the underlying `ora` driver. Could you share more information about the version of the Instantclient SDK + server you're using? I'm speculating the issue is a compatibility issue (likely in how the Go code uses the Instantclient SDK, and not with the Instantclient SDK itself) somewhere among the mess. If you could share an actual database dump that this can be easily reproduced on, it would help me to track down where the actual problem is occurring.

**Comment by kishorerathi** [comment]
@kenshaw, I used "Oracle Database 11g Enterprise Edition Release 11.2.0.2.0 - 64bit Production" client libraries for linux/ubuntu for Oracle support in usql. I also accessed the same DB table multiple times using sqlplus and razorSQL (a commercial gui tool for accessing various DB) and output was clean everytime. I can't share actual database dump because of obvious reasons, it belongs to somebody else.
My gut feel is that it is the layer between usql and oracle driver which may be messing it. And this being random in nature (i.e. sometime it happens on the first time and sometime it may happen on the 3rd execution..)
Hope this helps.

**Comment by kenshaw** [comment]
Thanks for the input. I definitely assume its a problem with the `ora` driver and the instantclient SDK. Are you using the same version of instantclient as the database? I would try compiling against 12+ of the instantclient SDK and trying that.

**Comment by kenshaw** [comment]
Please clarify what version of the database you're using -- you've presented two conflicting states above: using both the 11.2 and 12.2 database. 

`usql` has only ever been written / tested against instantclient 12.2.* and 12.1.*. While I believe the 12.* series of instantclient is backward compatible with the 11.* database, I remember Oracle having issues in the past. And yes, if you're trying to use instantclient 12.2.0.1.0  with the 12.2.0.2.0 database I imagine there might be small compatibility issues -- I would suggest using the latest instantclient SDK wherever possible.

I am not familiar with RazorSQL, but if you downloaded a pre-built binary with Oracle support, then the assumption is that whatever the embedded instantclient SDK that binary is using (or binding against) is compatible. Or, you have multiple instantclient SDKs installed, and RazorSQL is using the one that "works" properly with the installed database.

I'm not ruling out the possibility that `usql` has an error; but I would need significantly more information in order to actually track down where the issue is.
