### ISSUE TITLE
Cursor and prompt flicker on every keypress

### ISSUE THREAD

**Issue by lnicola** [xo/usql#496]
usql 0.19.12 on Linux, in GNOME Terminal. Not sure what's causing it.

**Comment by kenshaw** [comment]
This is because of syntax highlighting. If it bothers you, please turn off the syntax highlighting. It's more noticeable on slower computers.

**Comment by lnicola** [comment]
> This is because of syntax highlighting.

You're right, it stops flickering if I do `\set SYNTAX_HL false`. I still think it's a bug or limitation (there's no need to redraw the prompt, for example, or anything else that didn't change color), though.

> It's more noticeable on slower computers.

It's a 5950X :sob:.

**Comment by kenshaw** [comment]
@lnicola you would be surprised at how much work is involved in changing this. Believe it or not, I have been working specifically on this problem, which has required writing no less than 4 external, additional repos, some of which are more complex than `usql` itself. 

It's the culmination of more than a years worth of development time for me (note: I work on `usql` only in spare time). It is coming soon, but I don't really want to announce anything here until I'm closer to finishing it.

If you'd like to understand the technical reasons involved, and why it can't be easily fixed:

1. The syntax package (`chroma`) being used for syntax highlighting does not provide a re-entrant parser, and doesn't expose enough of its internal API to hook this directly
2. The `readline` package being used by `usql` only gives you the entire line, and not a character-by-character update; additionally, it only gives you the current line
3. Because of the above, what has to be done is the entire line (backing up to the prompt) has to be redrawn after each call to the readline package, and the internal state has to be kept to do this
4. As such, the internal parser (`stmt`) package that's used has to be re-applied multiple times to the entire buffer; when syntax highlighting is on, as the length of the active statement buffer grows, the flickering will become more and more prevalent/visible to the end user

To fix this, which I still haven't done, I have had to write a completely separate syntax highlighting package and a better `readline` replacement, in addition to other support packages associated with this. It is not trivial work, and I am working towards getting it done ASAP, but I can't really say when that might be.
