### ISSUE TITLE
Tab-completion for functions

### ISSUE THREAD

**Issue by lnicola** [xo/usql#497]
I didn't find an open issue for this, and it's not clear if it's supposed to be working, but it's not.

**Comment by kenshaw** [comment]
We don't have a list of functions for all the databases. Due to the sheer volume of work involved in trying to put all of these together for all the databases (even just the core databases), it's not likely tab completion will work for every single SQL functionality, in the same way as `psql`. Happy to entertain a well written PR that adds support for more metadata retrieval/completion!

**Comment by nineinchnick** [comment]
The issue description is not clear - are you saying it's not working at all, or for some drivers?

The autocompleter code can read functions from a driver: https://github.com/xo/usql/blob/master/drivers/completer/completer.go#L718
There are very few drivers that implement [the `FunctionReader` interface](https://github.com/xo/usql/blob/master/drivers/metadata/metadata.go#L96) though.

**Comment by lnicola** [comment]
I tested on Postgres and SQLite, functions and table names don't get completed. Feel free to close if it's expected.

**Comment by nineinchnick** [comment]
If this is a bug report, it might be a duplicate of https://github.com/xo/usql/issues/478

**Comment by lnicola** [comment]
Yeah, I just tested with 0.18.1 (on Postgres), I get a lot of completions there, although they're not great (no column names, no functions in the `select` column list). But functions do show up after `from`.

Closing, partly because it overlaps with #478, partly because completions probably need more work.
