### ISSUE TITLE
Mysql constraint work unexpectedly with usql.

### ISSUE THREAD

**Issue by xcccdjsn** [xo/usql#499]
This is my table.
```bash
-> my:localhost/flow_store=> desc category;
  Field   |       Type        | Null | Key | Default | Extra
----------+-------------------+------+-----+---------+-------
 name     | varchar(20)       | NO   | PRI |         |
 parent   | varchar(20)       | YES  |     |         |
 sort     | smallint unsigned | NO   | UNI |         |
 enable   | tinyint(1)        | NO   |     | 0       |
 icon_url | varchar(150)      | YES  |     |         |
(5 rows)
```

I successfully executed this commmand `-> my:localhost/flow_store=> insert into category (name, sort, enable) value ('111111111111111111121', 35, -1);` in usql, but I execute similar operation in mysql will fail.

**Comment by kenshaw** [comment]
Unless there's some kind of difference in your table definition, then the MySQL server does not report this as an error. I tried this locally:

```
my:localhost=> create table category (
my:localhost(>   name varchar(20) not null primary key,
my:localhost(>   parent varchar(20) null,
my:localhost(>   sort smallint unsigned not null unique,
my:localhost(>   enable tinyint(1) not null default 0,
my:localhost(>   icon_url varchar(150) null
my:localhost(> );
CREATE TABLE
my:localhost=> insert into category (name, sort, enable) value ('111111111111111111121', 35, -1);
INSERT 1
my:localhost=> select * from category;
         name         | parent | sort | enable | icon_url 
----------------------+--------+------+--------+----------
 11111111111111111112 |        |   35 |     -1 |  
(1 row)

my:localhost=> desc category;
  Field   |         Type         | Null | Key | Default | Extra 
----------+----------------------+------+-----+---------+-------
 name     | varchar(20)          | NO   | PRI |         |  
 parent   | varchar(20)          | YES  |     |         |  
 sort     | smallint(5) unsigned | NO   | UNI |         |  
 enable   | tinyint(1)           | NO   |     | 0       |  
 icon_url | varchar(150)         | YES  |     |         |  
(5 rows)

my:localhost=>  
```

I checked with the `mysql` command line client, and I believe this is due to a setting [that the `mysql`  client enables on the server](https://stackoverflow.com/questions/18897420/data-too-long-for-column-why), or it's some setting with the Go MySQL driver.

Considering there's a myriad number of configuration settings, you'll likely need to dig deep to find this. I'll try to look into it, and post back here if I find the specific setting, but I don't consider this a bug in `usql`. `usql` just reads/parses the statements and sends them off to the database. Compared to a database's native command line client (ie, `mysql`, `psql`, etc), it's much more independent, which requires a `usql` user to be more vigilant than otherwise using `mysql`/`psql`/etc.

My suggestion would be to figure out the specific setting that the `mysql` client enables when connecting to the server, and I'll consider making that the default setting in `usql`. Certainly, you'd then be able to use `usql`'s config/RC file to set this in the interim.

**Comment by kenshaw** [comment]
You might want to look at this: https://github.com/go-sql-driver/mysql/wiki/strict-mode

**Comment by kenshaw** [comment]
This is the output from `usql`:

```sh

my:localhost=> SELECT @@GLOBAL.sql_mode;
             @@GLOBAL.sql_mode              
--------------------------------------------
 NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 
(1 row)

my:localhost=> SELECT @@SESSION.sql_mode;
                     @@SESSION.sql_mode                      
-------------------------------------------------------------
 REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ANSI 
(1 row)

my:localhost=>  

```

Versus `mysql`:

```sh
MariaDB [mysql]> SELECT @@GLOBAL.sql_mode;
+--------------------------------------------+
| @@GLOBAL.sql_mode                          |
+--------------------------------------------+
| NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mysql]> SELECT @@SESSION.sql_mode;
+--------------------------------------------+
| @@SESSION.sql_mode                         |
+--------------------------------------------+
| NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mysql]> 

```

Then, if we set `STRICT_TRANS_TABLES` in `usql`:
```sh
my:localhost=> SET @@SESSION.sql_mode= 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES';
SET
my:localhost=> insert into category (name, sort, enable) value ('111111111111111111121', 35, -1);
error: mysql: 1406: Data too long for column 'name' at row 1
my:localhost=>  

```

So the setting you need here is `STRICT_TRANS_TABLES` on either your `@@GLOBAL.sql_mode` variable, or the `@@SESSION.sql_mode` variable.

Good luck!
