### ISSUE TITLE
Context deadline Exceeded

### ISSUE THREAD

**Issue by lorransr** [xo/usql#506]
After running some queries for more than a minute I get a message saying that the context deadline exceeded. Is there a way to override that?

**Comment by nineinchnick** [comment]
Which driver are you using?

**Comment by lorransr** [comment]
I'm using trino 😄

**Comment by nineinchnick** [comment]
Then you're in luck, because I'm also the maintainer of the Trino Go client. There's a default timeout of 60 seconds for all queries, but unfortunately, it's not configurable via the URL parameters. Can you open an issue about it in https://github.com/trinodb/trino-go-client? I'll close this one, since it's not a problem with usql, just the Trino driver.
