### ISSUE TITLE
Error on comment lines in Oracle....

### ISSUE THREAD

**Issue by kishorerathi** [xo/usql#61]
I am using the following syntax for comments in Oracle

select sysdate from dual;    -- some comment 

-- some comment by itself

And I get the error    "error: ora: ORA-24374: define not done before fetch or execute and fetch"

This happens in interactive or interactive mode. What am I missing in the comment syntax. Thanks

**Comment by kenshaw** [comment]
I don't believe this is a problem with `usql`, and I'm not able to replicate this behavior on Oracle. Can you provide more information about the sequence of queries you executed? For the record, this is what I get when testing with an empty test database:

```sh
or:booktest@localhost/xe=> select sysdate from dual; -- test
           sysdate           
+---------------------------+
  2018-06-19T23:39:08+07:00  
(1 rows)

or:booktest@localhost/xe-> --comment
or:booktest@localhost/xe-> \p
-- test
--comment
or:booktest@localhost/xe-> \g
error: ora: ORA-00900: invalid SQL statement
or:booktest@localhost/xe=>  
```

Understand that `usql` parses a SQL statement and it is sent to the database when either a  `;` is encountered (outside of a string literal, and when the query's parentheses are balanced) or when manually sent by the ` \g` metacommand. As such, this is 2 statements that `usql` is sending. 

Here is a breakdown of what is happening underneath the hood with `usql`:

1.  The user enters `select sysdate from dual; -- test`.
2. `usql` parses this, and sees that there is a "ready" statement (`select sysdate from dual;`), as it is terminated with a semicolon, and thus is sent to the database.
3. Next, the query buffer is cleared, and then a new query is started. It is initially populated with `-- test` as that that has not yet been sent to the database. 
4. The user enters `--comment` on the next line, and `usql` appends it to the query buffer (along with a separating newline).
5. The query buffer is not "ready", and `usql` indicates this by the `->` prompt. 
4. The user enters the metacommand `\p` (aka `\print`), causing `usql` to print the current query buffer that that has been accumulated. In this case, `-- test\n--comment`. 
5. The user enters the metacommand `\g`,  forcing the query buffer to be executed (ie, sent to the database). 
6. Because the statement  sent to the database contains only comments, Oracle reports back that it is an `invalid SQL statement`.

If you can provide a way to reproduce the `ORA-24374` error, let me know and I'll gladly investigate. Personally, I've never seen this error from an Oracle database and I don't believe this was not a `usql` error.
