### ISSUE TITLE
Error Install usql via Go on Arch Linux

### ISSUE THREAD

**Issue by viniciusrdacosta** [xo/usql#62]
I'm trying to install usql via go using the command: `go get -u -tags all github.com/xo/usql` but I'm getting the following error:
```
# github.com/alexbrainman/odbc/api
go/src/github.com/alexbrainman/odbc/api/api_unix.go:12:11: fatal error: sql.h:
No such file or directory
 // #include <sql.h>
           ^~~~~~~
compilation terminated.
# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
Package 'oci8', required by 'virtual:world', not found
pkg-config: exit status 1
```

My Go version is `go1.10.3 linux/amd64` and I'm using Arch Linux

**Comment by kenshaw** [comment]
You're building with the `-tag 'all'` -- this includes Oracle and ODBC support, both of which require third-party C dependencies. For ODBC, at least, most Linux distributions have a package named `unixodbc` or `unixodbc-dev` that you can easily install:

```sh
# on debian/ubuntu systems
$ sudo apt install unixodbc unixodbc-dev

# on arch systems
$ sudo pacman -S unixodbc

# additionally on macOS
$ brew install unixodbc
```

Building Oracle is a bit more tough, as it requires downloading Oracle's Instantclient SDK and installing it / configuring it to work properly with `pkg-config`, which I will not cover here.

I would suggest that instead of building with `-tag all` that you instead build with `-tag most`, which is the same as `all` but excludes the ODBC and Oracle drivers. Most users are unlikely to need ODBC or Oracle drivers -- and likely if you do, you probably already have them installed / configured.
