### ISSUE TITLE
usql: error while loading shared libraries: libicuuc.so.60: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by elvizlai** [xo/usql#80]
alpine docker image with glibc and icu-libs but not work.

```
bash-4.4# find / -name libicuuc.so.* 2>/dev/null
/usr/lib/libicuuc.so.60.2
/usr/lib/libicuuc.so.60
```

**Comment by kenshaw** [comment]
Please build from source. This is a dependency from one of the SQLite3 features. If you need a full static build, you'll need to make sure you don't build with the `sqlite_icu` build tag (which the releases use).

**Comment by vn971** [comment]
@kenshaw just curious, why doesn't it show up in `ldd`?
```
ldd usql-0.7.1
	not a dynamic executable
```

Also, personally, I would very much support building in such a way that sqlite_icu from the host system is not required.
Otherwise, the official installation procedure is broken, isn't it?: https://github.com/xo/usql#installing-via-release   Or if we officially require installation of said library on host system, that's a correct solution as well...

By the way, it's probably known already, but without `sqlite_icu`, 0.7.0 does work while 0.7.1 doesn't.

**Comment by vn971** [comment]
To answer my own question on `ldd`. It probably doesn't show up there because the binary is probably `upx`-ed. The question on official docs on installation still holds though.
